function getOrders() {
    return [
        {
            ID: '1',
            CustomerName: 'Ernest Hemingway',
            Street: 'K.Barona 5',
            City: 'Illinois',
            Country: 'USA',
            Quantity: '5',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€90.75',
            Status: 'Pending',
        },
        {
            ID: '2',
            CustomerName: 'Mark Twain',
            Street: 'K.Barona 5',
            City: 'Florida',
            Country: 'USA',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€181.50',
            Status: 'Pending',
        },
        {
            ID: '3',
            CustomerName: 'Virginia Woolf',
            Street: 'K.Barona 5',
            City: 'Riga',
            Country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '4',
            CustomerName: 'Kurt Vonnegut',
            Street: 'K.Barona 5',
            City: 'Riga',
            Country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '5',
            CustomerName: 'Agatha Christie',
            Street: 'K.Barona 5',
            City: 'London',
            Country: 'England',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '6',
            CustomerName: 'Gabriel Garcia Marquez',
            Street: 'K.Barona 5',
            City: 'Aracataca',
            Country: 'Colombia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '7',
            CustomerName: 'J.K. Rowling',
            Street: 'K.Barona 5',
            City: 'Yate',
            Country: 'England',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '8',
            CustomerName: 'Roald Dahl',
            Street: 'K.Barona 5',
            City: 'Llandaff',
            Country: 'Wales',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '9',
            CustomerName: 'Fyodor Dostoevsky',
            Street: 'K.Barona 5',
            City: 'Moscow',
            Country: 'Russia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '10',
            CustomerName: 'Isabel Allende',
            Street: 'K.Barona 5',
            City: 'Lima',
            Country: 'Peru',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
    ]
}

export default getOrders