function getOrders() {
    return [
        {
            ID: '1',
            CustomerName: 'Ernest',
            Surname: 'Hemingway',
            Street: 'Fareweel street 3',
            City: 'Illinois',
            Country: 'USA',
            Quantity: '5',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€90.75',
            Status: 'Pending',
            color: 'orange',
        },
        {
            ID: '2',
            CustomerName: 'Mark',
            Surname: 'Twain',
            Street: 'Prince street 21',
            City: 'Florida',
            Country: 'USA',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€181.50',
            Status: 'Completed',
            color: 'green',
        },
        {
            ID: '3',
            CustomerName: 'Virginia',
            Surname: 'Woolf',
            Street: 'Brivibas 18',
            City: 'Riga',
            Country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Canceled',
            color: 'red',
        },
        {
            ID: '4',
            CustomerName: 'Kurt',
            Surname: 'Vonnegut',
            Street: 'K. Barona 5',
            City: 'Riga',
            Country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
            color: 'orange',
        },
        {
            ID: '5',
            CustomerName: 'Agatha',
            Surname: 'Christie',
            Street: 'Puaro street 2',
            City: 'London',
            Country: 'England',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
            color: 'orange',
        },
        {
            ID: '6',
            CustomerName: 'Gabriel Garcia',
            Surname: 'Marquez',
            Street: 'Cholera street 9',
            City: 'Aracataca',
            Country: 'Colombia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Completed',
            color: 'green',
        },
        {
            ID: '7',
            CustomerName: 'J.K.',
            Surname: 'Rowling',
            Street: 'Hogwarts street 1',
            City: 'Yate',
            Country: 'England',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Canceled',
            color: 'red',
        },
        {
            ID: '8',
            CustomerName: 'Roald',
            Surname: 'Dahl',
            Street: 'Matildas street 7',
            City: 'Llandaff',
            Country: 'Wales',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
            color: 'orange',
        },
        {
            ID: '9',
            CustomerName: 'Fyodor',
            Surname: 'Dostoevsky',
            Street: 'Gogola street 8',
            City: 'Moscow',
            Country: 'Russia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
            color: 'orange',
        },
        {
            ID: '10',
            CustomerName: 'Isabel',
            Surname: 'Allende',
            Street: 'Chocolate street 5',
            City: 'Lima',
            Country: 'Peru',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
            color: 'orange',
        },
    ]
}

export default getOrders