function getOrders() {
    return [
        {
            ID: '1',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '2',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '3',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '4',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '5',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '6',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '7',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '8',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '9',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
        {
            ID: '10',
            CustomerName: 'Juris Kalnins',
            Street: 'K.Barona 5',
            City: 'Riga',
            Post: 'LV-2111',
            country: 'Latvia',
            Quantity: '10',
            Price: '€15.00 ',
            VAT: '€3.15',
            Total: '€18.15',
            Status: 'Pending',
        },
    ]
}

export default getOrders