function getProducts() {
    return [
        {
            title: 'Three Succulent Plants',
            number: '01',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/796620/pexels-photo-796620.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
            discountPrice: 18,
        },
        {
            title: 'Ficus Elastica or Rubber Plant',
            number: '02',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/20053/rubber-plant.jpg?width=720&center=0.0,0.0',
            price: 25,
            discountPrice: 1.8,
        },
        {
            title: 'Maidenhair Fern',
            number: '03',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/20051/maidenhair-fern.jpg?width=720&center=0.0,0.0',
            price: 9,
        },
        {
            title: 'Zanzibar Gem',
            number: '04',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/3178/gettyimages-488755246-web.jpg?width=720&center=0.0,0.0',
            price: 18,
        },
        {
            title: 'Small palm',
            number: '05',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/1974508/pexels-photo-1974508.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 23,
        },
        {
            title: 'Sansevieria or Mother-in-law`s Tongue',
            number: '06',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/3175/gettyimages-503954672-web.jpg?width=720&center=0.0,0.0',
            price: 29,
        },
        {
            title: 'Spathiphyllum or Peace lily',
            number: '07',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/20052/peace-lily.jpg?width=720&center=0.0,0.0',
            price: 31,
        },
        {
            title: 'Pottet plant',
            number: '08',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/8988961/pexels-photo-8988961.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
        },
        {
            title: 'Epipremnum aureum or Devil`s Ivy',
            number: '09',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/20049/devils-ivy.jpg?width=720&center=0.0,0.0',
            price: 20,
        },
        {
            title: 'Swiss cheese plant',
            number: '10',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.bhg.com.au/media/20046/monstera-deliciosa.jpg?width=720&center=0.0,0.0',
            price: 25,
        },
        {
            title: 'Monstera',
            number: '11',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://media.istockphoto.com/photos/monstera-in-a-pot-isolated-on-white-background-close-up-of-tropical-picture-id1278906674?k=20&m=1278906674&s=612x612&w=0&h=udI6hjjVdHQl8VOfenSf4YSPObrcmruBMYeaL8SNVE4=',
            price: 35,
        },
        {
            title: 'White pot',
            number: '12',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/970089/pexels-photo-970089.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 21,
        },
        {
            title: 'Green plant',
            number: '13',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.squarespace-cdn.com/content/v1/53ece0c8e4b0cc5a9ece7d53/1540221568101-JFI76L26YBU04YRC9S6B/Plant_Pot_002.jpg?format=1000w',
            price: 15,
        },
        {
            title: 'Succulent',
            number: '14',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGxhbnQlMjBwb3R8ZW58MHx8MHx8&w=1000&q=80',
            price: 14,
        },
        {
            title: 'Flowers',
            number: '15',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/8096798/pexels-photo-8096798.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 5.5,
        },
        {
            title: 'Dracaena trifasciata',
            number: '16',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://cdn.shopify.com/s/files/1/1706/1307/products/Sansevieria-zeylanica-Snake-Plant-Esra-Graphite-Plant-Pot_1200x.jpg?v=1622809957',
            price: 24,
        },
        {
            title: 'Three palms',
            number: '17',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://i.pinimg.com/originals/e0/59/de/e059de3d57c4423db3682669bf7be05a.jpg',
            price: 27,
        },
        {
            title: 'Small palm',
            number: '18',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://m.media-amazon.com/images/I/718W3zQb-5S._SL1500_.jpg',
            price: 31,
        },
        {
            title: 'Hyacinth',
            number: '19',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/87581/pexels-photo-87581.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 5.5,
        },
        {
            title: 'Green Cactus',
            number: '20',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/219779/pexels-photo-219779.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 25,
        },

    ]
}

export default getProducts