function getProducts() {
    return [
        {
            title: 'Cat blanket',
            number: '01',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/7211201/pexels-photo-7211201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
            discountPrice: 18,
        },
        {
            title: 'Spring Into Action',
            number: '02',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/71301_PT5._AC_SL1500_V1525718864_.jpg',
            price: 2,
            discountPrice: 1.8,
        },
        {
            title: 'On the Ball',
            number: '03',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/91kDN7yvZRL._SL1500_.jpg',
            price: 9,
        },
        {
            title: 'Cat Scratch Fever',
            number: '04',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/5191043.jpeg',
            price: 8,
        },
        {
            title: 'Jingle Jangle',
            number: '05',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/GUEST_8a57d83d-2584-4d24-919a-8d00b91ee80c.jpeg',
            price: 2,
        },
        {
            title: 'Blue plastic basin',
            number: '06',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/10914514/pexels-photo-10914514.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 30,
        },
        {
            title: 'Cat scratcher',
            number: '07',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://cdn.thewirecutter.com/wp-content/media/2020/11/catgifts-2048px-1257.jpg?auto=webp&quality=75&width=980&dpr=2',
            price: 69,
        },
        {
            title: 'Cat basket',
            number: '08',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/7508190/pexels-photo-7508190.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
        },
        {
            title: 'Cat duck',
            number: '09',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/8935990/pexels-photo-8935990.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
        },
        {
            title: 'Cat laser',
            number: '10',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.thesprucepets.com/thmb/KsQnc5dgbAkwS4O8uGoI3fQKMsI=/900x0/filters:no_upscale():max_bytes(150000):strip_icc()/FroliCatBOLTLaserPetToy-601df1f3d3e04da6b36b12ba4c84384f.jpg',
            price: 25,
        },
        {
            title: 'Colorful eggs',
            number: '11',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/10854625/pexels-photo-10854625.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 3,
        },
        {
            title: 'Spring Into Action',
            number: '12',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/71301_PT5._AC_SL1500_V1525718864_.jpg',
            price: 2,
        },
        {
            title: 'On the Ball',
            number: '13',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/91kDN7yvZRL._SL1500_.jpg',
            price: 9,
        },
        {
            title: 'Cat Scratch Fever',
            number: '14',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://static.parade.com/wp-content/uploads/2018/12/5191043.jpeg',
            price: 8,
        },
        {
            title: 'Flowers',
            number: '15',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/8096798/pexels-photo-8096798.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 5.5,
        },
        {
            title: 'Mermaid cat',
            number: '16',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/994172/pexels-photo-994172.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 24,
        },
        {
            title: 'Cat scratcher',
            number: '17',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://cdn.thewirecutter.com/wp-content/media/2020/11/catgifts-2048px-1257.jpg?auto=webp&quality=75&width=980&dpr=2',
            price: 69,
        },
        {
            title: 'Chess piece',
            number: '18',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/792051/pexels-photo-792051.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 3,
        },
        {
            title: 'Cat duck',
            number: '19',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://images.pexels.com/photos/8935990/pexels-photo-8935990.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            price: 20,
        },
        {
            title: 'Cat laser',
            number: '20',
            describtione: 'I like cats because they are fat and fluffy sleep, sleep over your phone and make cute snoring noises yet sleep on dog bed, force dog to sleep on floor.',
            image: 'https://www.thesprucepets.com/thmb/KsQnc5dgbAkwS4O8uGoI3fQKMsI=/900x0/filters:no_upscale():max_bytes(150000):strip_icc()/FroliCatBOLTLaserPetToy-601df1f3d3e04da6b36b12ba4c84384f.jpg',
            price: 25,
        },

    ]
}

export default getProducts